language: php
php:
  - 7.3

sudo: enabled
before_script:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo mkdir _build
  - cd _build
  - sudo cmake ..
  - sudo make
  - sudo cp libgtest* /usr/lib/
  - sudo git clone https://github.com/arun11299/cpp-jwt.git
  - cd cpp-jwt
  - sudo mkdir _build
  - cd _build
  - sudo cmake ..
  - sudo make install

script:
  - phpize
  - ./configure --enable-extjwt
  - make test