language: php
php:
  - 7.3

sudo: enabled
addons:
  apt:
    packages:
      - cmake

before_install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo mkdir _build
  - cd _build
  - sudo cmake ..
  - sudo make
  - sudo cp libgtest* /usr/lib/
  - cd /usr/src
  - sudo mkdir jwtcpp
  - sudo git clone https://github.com/Thalhammer/jwt-cpp.git jwtcpp

script:
  - phpize
  - ./configure --enable-extjwt --with-jwtcpp=/usr/src/jwtcpp/include/jwt-cpp
  - make test